{
    "Message": "An error has occurred.",
    "ExceptionMessage": "An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information.",
    "ExceptionType": "System.Security.Cryptography.CryptographicException",
    "StackTrace": "  at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect (System.Byte[] plaintext) [0x0010d] in <f79bdd8e96d54cc399a5ddb59e587466>:0 \n  at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Protect (Microsoft.AspNetCore.DataProtection.IDataProtector protector, System.String plaintext) [0x00029] in <7acb165d12504a8b8745ea4b3d51f224>:0 \n  at Kudu.Core.Infrastructure.SecurityUtility.GenerateSecretStringsKeyPair (System.Int32 number) [0x00022] in <7785b4c12a7749dea1c09312b9685a87>:0 \n  at Kudu.Core.Functions.FunctionManager+<GetKeyObjectFromFile>d__9`1[T].MoveNext () [0x000cf] in <7785b4c12a7749dea1c09312b9685a87>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at Kudu.Core.Functions.FunctionManager+<GetMasterKeyAsync>d__11.MoveNext () [0x0006a] in <7785b4c12a7749dea1c09312b9685a87>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at Kudu.Services.Functions.FunctionController+<GetMasterKey>d__11.MoveNext () [0x000a5] in <798f79da9afd4431aba8190558e43b3c>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Threading.Tasks.TaskHelpersExtensions+<CastToObject>d__3`1[T].MoveNext () [0x00063] in <f99f496cb0d249c1a945c1fcabce1695>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Web.Http.Controllers.ApiControllerActionInvoker+<InvokeActionAsyncCore>d__0.MoveNext () [0x000c7] in <f99f496cb0d249c1a945c1fcabce1695>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__5.MoveNext () [0x0009d] in <f99f496cb0d249c1a945c1fcabce1695>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__5.MoveNext () [0x001f6] in <f99f496cb0d249c1a945c1fcabce1695>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Web.Http.Filters.ActionFilterAttribute+<ExecuteActionFilterAsyncCore>d__0.MoveNext () [0x0011b] in <f99f496cb0d249c1a945c1fcabce1695>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__5.MoveNext () [0x0009d] in <f99f496cb0d249c1a945c1fcabce1695>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__5.MoveNext () [0x001f6] in <f99f496cb0d249c1a945c1fcabce1695>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Web.Http.Filters.ActionFilterAttribute+<ExecuteActionFilterAsyncCore>d__0.MoveNext () [0x0011b] in <f99f496cb0d249c1a945c1fcabce1695>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Web.Http.Controllers.ActionFilterResult+<ExecuteAsync>d__2.MoveNext () [0x001f1] in <f99f496cb0d249c1a945c1fcabce1695>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <26675363164d4ecaa42023d32f6372d2>:0 \n  at System.Web.Http.Controllers.ExceptionFilterResult+<ExecuteAsync>d__0.MoveNext () [0x00097] in <f99f496cb0d249c1a945c1fcabce1695>:0 ",
    "InnerException": {
        "Message": "An error has occurred.",
        "ExceptionMessage": "The key ring does not contain a valid default protection key. The data protection system cannot create a new key because auto-generation of keys is disabled.",
        "ExceptionType": "System.InvalidOperationException",
        "StackTrace": "  at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore (System.DateTimeOffset now, Microsoft.AspNetCore.DataProtection.KeyManagement.IKey keyJustAdded) [0x000bf] in <f79bdd8e96d54cc399a5ddb59e587466>:0 \n  at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing (System.DateTimeOffset now) [0x00000] in <f79bdd8e96d54cc399a5ddb59e587466>:0 \n  at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore (System.DateTime utcNow) [0x000c9] in <f79bdd8e96d54cc399a5ddb59e587466>:0 \n  at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing () [0x00006] in <f79bdd8e96d54cc399a5ddb59e587466>:0 \n  at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect (System.Byte[] plaintext) [0x0001d] in <f79bdd8e96d54cc399a5ddb59e587466>:0 "
    }
}